apiVersion: v1
kind: ConfigMap
metadata:
  namespace: nginx-example
  name: nginx-config
data:
  nginx.conf:
    server {
      listen 80;
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
      location /metrics {
        stub_status on;
        access_log off;
      }
    }
  index.html:
    <h1> Hello World </h1>
